// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;
using UserSysCore;

namespace UserSysCore.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20180206142941_menu")]
    partial class menu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("UserSysCore.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionName");

                    b.Property<string>("ControllerName");

                    b.Property<bool>("IsDisplay");

                    b.Property<string>("MenuMemo")
                        .HasMaxLength(64);

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<int>("MenuPId");

                    b.Property<int>("OrderId");

                    b.HasKey("MenuId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("UserSysCore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreatorId");

                    b.Property<string>("ProductDes");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<string>("ProductUrl");

                    b.HasKey("ProductId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("UserSysCore.Models.RoleInfo", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("RoleMemo");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.HasKey("RoleId");

                    b.ToTable("RoleInfo");
                });

            modelBuilder.Entity("UserSysCore.Models.RoleToMenu", b =>
                {
                    b.Property<int>("RoleToMenuId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MenuId");

                    b.Property<int>("RoleId");

                    b.HasKey("RoleToMenuId");

                    b.ToTable("RoleToMenu");
                });

            modelBuilder.Entity("UserSysCore.Models.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<string>("LoginPwd")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("UserName")
                        .HasMaxLength(16);

                    b.HasKey("UserId");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("UserSysCore.Models.UserToRole", b =>
                {
                    b.Property<int>("UserToRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("UserToRoleId");

                    b.ToTable("UserToRole");
                });

            modelBuilder.Entity("UserSysCore.Models.Product", b =>
                {
                    b.HasOne("UserSysCore.Models.UserInfo", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
